config/routes.rb
Rails.application.routes.draw do
  devise_for :views
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'recipes#index'
  resources :recipes do
    resources :comments
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  validates :user_id, presence: true
  validates :image, presence: true

  has_attached_file :image, styles: { medium: "500x500>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

  belongs_to :user
  has_many :comments


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :recipes, dependent: :destroy
  has_many :comments, dependent: :destroy


end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_recipe

  def create
    recipe_id = params[:recipe_id]
    @recipe = Recipe.find(recipe_id)
    @comment = @recipe.comments.create(comment_params.merge(user_id: current_user.id, recipe_id: recipe_id))
    redirect_to recipes_path
    # @comment = @recipe.comments.build(comment_params)
    # @comment.user_id = current_user.id
    #
    # if @comment.save
    #   respond_to do |format|
    #     format.html { redirect_to root_path }
    #     format.js
    #   end
    #   # flash[:notice] = "You commented the hell out of that post!"
    #   # redirect_to :back
    # else
    #   flash[:alert] = "Check the comment form, something went  wrong."
    #   render root_path
    # end
  end

  # def destroy
  #   @comment = @recipe.comments.find(params[:id])
  #   if @comment.user_id == current_user.id
  #     @comment.delete
  #     respond_to do |format|
  #       format.html { redirect_to root_path }
  #       format.js
  #     end
  #   end
  #  # flash[:notice] = "Comment deleted :("
  #  # redirect_to root_path
  # end

  private

    def comment_params
      params.require(:comment).permit(:content, :recipe_id, :user_id)
    end

    def set_recipe
      recipe_id = params[:recipe_id]
      @recipe = Recipe.find(params[:recipe_id])
    end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  def new
    @recipe = Recipe.new
  end

  def index
    @recipes = Recipe.all.order('created_at DESC')
  end

  # def show
  #   @recipe = Recipe.find(params[:id])
  # end

  def create
    @recipe = Recipe.new(post_params.merge(user_id: current_user.id))
    if @recipe.save
      flash[:notice] = "Your post has been created!"
      redirect_to recipes_path
    else
      flash[:alert] = "Upload failed"
      render :new
    end
  end

  def edit
    @recipe = Recipe.find(params[:id])
  end

  def update
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      if @recipe.update(post_params)
        flash[:notice] = "Recipe updated."
        redirect_to recipes_path
      else
        flash[:alert] = "Update failed.  Please check the form."
        render :edit
      end
    else
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    if current_user == @recipe.user
      @recipe.destroy
      flash[:notice] = "Recipe deleted."
      redirect_to recipes_path
    else
      flash[:alert] = "That post doesn't belong to you!"
      redirect_to root_path
    end
  end

  private
    def post_params
      params.require(:recipe).permit(:image, :description, :user_id)
    end

    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # def my_recipe
    #   if current_user == @recipe.user
    #     @recipe.destroy
    #     flash[:notice] = "Recipe deleted."
    #     redirect_to recipes_path
    #   else
    #     flash[:alert] = "That post doesn't belong to you!"
    #     redirect_to root_path
    #   end
    # end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:email, :user_name, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/comments/_form.html.erb
<%= form_for([@recipe, @recipe.comments.build]) do |form| %>

  <%= image_tag @recipe.image.url(:medium) %><br>
 <h2>Add your comment</h2>

  <div class="field">
    <%= form.text_area :content %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.js.erb
$('#comments_<%= @recipe.id %>').append("<%=j render 'comments/comment', recipe: @recipe, comment: @comment %>");
$('#comment_content_<%= @recipe.id %>').val('')

app/views/comments/delete.js.erb
$('#comments_<%= @recipe.id %>').html("<%= j render @recipe.comments, recipe: @recipe, comment: @comment %>");

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form', comment: @comment %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<h1>Comments</h1>

<table>
  <thead>
    <tr>
      <th>Body</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.content %></td>
        <td><%= comment.recipe_id %></td>
        <td><%= comment.user_id %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/comments/new.html.erb
<%= render 'form', comment: @comment %>

<%= link_to 'Back', recipes_path %>

app/views/comments/show.html.erb
<p>
  <strong>Body:</strong>
  <%= @comment.content %>
</p>

<p>
  <strong>Recipe:</strong>
  <%= @comment.recipe_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @comment.user_id %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cookerygram</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <h2><%= link_to "Cookerygram", recipes_path, {:class => 'nav-link'} %></h2>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active"><h4>
            <% if current_user %>
              <%= link_to "New Recipe", new_recipe_path, {:class => 'nav-link'} %>
            <% end %>
          </h4></li>

        </ul>
        <form class="form-inline my-2 my-lg-0">
          <p class="navbar-text pull-right">
            <% if user_signed_in? %>
            Logged in as <strong><%= current_user.email %></strong>.
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link', confirm: 'are you sure?'  %>
            <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
            <% end %>
          </p>
        </form>
      </div>
    </nav>
    <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for @recipe, html: { multipart: true } do |f| %>


 <div class="field">
   <%= f.label :description %><br>
   <%= f.text_area :description %>
 </div>
 <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>

 <div class="actions">
   <%= f.submit %>
 </div>
<% end %>

app/views/recipes/edit.html.erb
<h1>Editing Recipe post</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/index.html.erb
<h1> Everyone's beatiful recipes </h1>
<ul class="recipes-list">
  <br>
<% if user_signed_in? %>
  <%= link_to 'New recipe', new_recipe_path %><br><br>
  <% @recipes.each do |recipe| %>
  <div class="post-recipes" id='recipe_<%=recipe.id %>'>
    <br>
    <h2><%= recipe.user.user_name %></h2><br>
    <%= image_tag recipe.image.url(:medium) %><br>
    <%= recipe.description %><br>
    <%= recipe.created_at.strftime('Posted at %I:%M%p, %d/%m/%Y') %><br>
    <% if recipe.user_id == current_user.id %>
    <%= link_to 'Edit Recipe', edit_recipe_path(recipe)%>
    <%= link_to 'Delete', recipe, method: :delete, data: { confirm: 'Are you sure?' } %>
    <br>
    <%end%>
    <br>

    <%= link_to 'Add Comment', new_recipe_comment_path(recipe.id), method: :get %><br>
    <br>
    <% recipe.comments.each do |comment| %>
    <div id="comment_<%=comment.id %>">
      <strong><%= comment.user.user_name %></strong>
      <%= comment.content %><br>
      <%= comment.created_at.strftime('Posted at %I:%M%p, %d/%m/%Y') %><br>
    </div>
    <br>
      <% end%>
    </div>
  <% end %>
<% end %>
</ul>

app/views/recipes/new.html.erb
<h1>New Recipe Post</h1>

<%= render 'form', recipe: @recipe %>

<%= link_to 'Back', recipes_path %>

app/views/recipes/show.html.erb
<h1>Your recipe</h1>

<div id="centered" class="white">
  <%= @recipe.user_name %>
  <%= image_tag(@recipe.image.url(:medium)) %>
  <br>
  <%= @recipe.description %>
</div>

<%= link_to 'Edit', edit_recipe_path(@recipe) %> |
<%= link_to 'Back', recipes_path %>